In [1]:
#https://reports.openmail.com/v1/campaign.json?auth_key=d4HamgV1p0sRtIP6mlMO&days=31

import requests, csv, json
import json
import pandas as pd
import numpy as np
import matplotlib as mtlp
import os

In [2]:
os.getcwd()

'c:\\Users\\LENOVO\\Documents\\REPORTES ARBITRAJE\\Octubre 2023\\informe Python'

In [3]:
#cargamos los datos json en df
url = 'https://reports.openmail.com/v1/campaign.json?auth_key=d4HamgV1p0sRtIP6mlMO&days=5'
Reporte_S1 = pd.read_json(url)
print(Reporte_S1.head())

           0                                          1               2   \
0        Date                            Campaign Domain  Total Sessions
1  2023-11-01           a-great-ar-cadena-de-bloques.fyi              20
2  2023-11-01               a-great-ar-coches-usados.fyi              20
3  2023-11-01                     a-great-ar-crucero.fyi              33
4  2023-11-01  a-great-ar-ofertas-de-telefonia-movil.fyi              32

                3                 4                  5             6   \
0  Mobile Sessions  Desktop Sessions  Mobile Sessions %  Distinct IPs
1               15                 5                 75             6
2                3                17                 15            10
3               30                 3              90.91             9
4               17                15              53.13            13

                    7                     8                      9         10  \
0  Distinct Mobile IPs  Distinct Desktop IPs  Distinct Mobile IPs %  Searches
1                    3                     3                     50         0
2                    3                     7                     30         0
3                    6                     3                  66.67         0
4                    5                     8                  38.46         3

       11                       12                   13                  14  \
0  Clicks  Estimated Gross Revenue  Revenue Per Session  Revenue Per Search
1       0                        0                    0                   0
2       0                        0                    0                   0
3       0                        0                    0                   0
4       0                        0                    0                   0

               15                 16                    17
0  Revenue Per IP  Revenue Per Click  Clicks Per Session %
1               0                  0                     0
2               0                  0                     0
3               0                  0                     0
4               0                  0                     0

In [4]:
Reporte_S1.reset_index(drop=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Date,Campaign Domain,Total Sessions,Mobile Sessions,Desktop Sessions,Mobile Sessions %,Distinct IPs,Distinct Mobile IPs,Distinct Desktop IPs,Distinct Mobile IPs %,Searches,Clicks,Estimated Gross Revenue,Revenue Per Session,Revenue Per Search,Revenue Per IP,Revenue Per Click,Clicks Per Session %
1,2023-11-01,a-great-ar-cadena-de-bloques.fyi,20,15,5,75,6,3,3,50,0,0,0,0,0,0,0,0
2,2023-11-01,a-great-ar-coches-usados.fyi,20,3,17,15,10,3,7,30,0,0,0,0,0,0,0,0
3,2023-11-01,a-great-ar-crucero.fyi,33,30,3,90.91,9,6,3,66.67,0,0,0,0,0,0,0,0
4,2023-11-01,a-great-ar-ofertas-de-telefonia-movil.fyi,32,17,15,53.13,13,5,8,38.46,3,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362,2023-11-05,work-as-an-au-pair-in-usa.xyz,8,1,7,12.5,6,1,5,16.67,0,0,0,0,0,0,0,0
6363,2023-11-05,work-from-home-1562001.fyi,3,0,3,0,3,0,3,0,0,0,0,0,0,0,0,0
6364,2023-11-05,work-in-australia-intl.fyi,1229,1207,22,98.21,1076,1056,21,98.14,1085,625,35.02,0.03,0.03,0.03,0.06,50.85
6365,2023-11-05,work-visa-intl.xyz,4,4,0,100,4,4,0,100,0,0,0,0,0,0,0,0
6366,2023-11-05,yachts-2833.info,41,0,41,0,4,0,4,0,0,0,0,0,0,0,0,0

In [5]:
Reporte_S1.style.hide(axis="index")
Reporte_S1[2]

0       Total Sessions
1                   20
2                   20
3                   33
4                   32
             ...
6362                 8
6363                 3
6364              1229
6365                 4
6366                41
Name: 2, Length: 6367, dtype: object

In [6]:
#Reporte_S1.drop([0], axis=0, inplace=True)

Reporte_S1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Date,Campaign Domain,Total Sessions,Mobile Sessions,Desktop Sessions,Mobile Sessions %,Distinct IPs,Distinct Mobile IPs,Distinct Desktop IPs,Distinct Mobile IPs %,Searches,Clicks,Estimated Gross Revenue,Revenue Per Session,Revenue Per Search,Revenue Per IP,Revenue Per Click,Clicks Per Session %
1,2023-11-01,a-great-ar-cadena-de-bloques.fyi,20,15,5,75,6,3,3,50,0,0,0,0,0,0,0,0
2,2023-11-01,a-great-ar-coches-usados.fyi,20,3,17,15,10,3,7,30,0,0,0,0,0,0,0,0
3,2023-11-01,a-great-ar-crucero.fyi,33,30,3,90.91,9,6,3,66.67,0,0,0,0,0,0,0,0
4,2023-11-01,a-great-ar-ofertas-de-telefonia-movil.fyi,32,17,15,53.13,13,5,8,38.46,3,0,0,0,0,0,0,0

In [7]:
#Borramos columnas
Reporte_S1_limpio_Nov = Reporte_S1.drop([2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17], axis=1)

In [9]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
from gspread_pandas import Spread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from gspread import Worksheet


# ruta de la credencial json
credentials_file = 'C:\\Users\\LENOVO\Documents\\REPORTES ARBITRAJE\\Octubre 2023\\informe Python\\my-project-20012-1675399697547-781c2b16d62b.json'

# Se establece el alcance y crea un cliente autorizado
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name(credentials_file, scope)
gc = gspread.authorize(credentials)

# se abre la hoja de cálculo por su ID o URL
spreadsheet_id = '1D87RosPYFtaZ-07YQUBeZrETxCrbJ-h_Zklpni6-lvg'
worksheet_name = 'Noviembre 2023'  # Puedes especificar el nombre de la hoja

# se abre la hoja de cálculo
sh = gc.open_by_key(spreadsheet_id)

# Se selecciona la hoja de cálculo por su nombre
worksheet = sh.worksheet(worksheet_name)

# se carga el df limpio en un objeto de datos de Google Sheets
df_sheets = pd.DataFrame(Reporte_S1_limpio_Nov)  #Reporte_S1


#---------- #Todo ESTO es para reescribir encima

# Obtiene los datos existentes en la hoja de cálculo y los almacena en un DataFrame
#existing_data = pd.DataFrame(worksheet.get_all_records())

# Ahora, puedes cargar tus nuevos datos en el DataFrame `existing_data` y luego escribir todo de nuevo en la hoja de cálculo
#new_data = pd.DataFrame(Reporte_S1_limpio_Nov)

# Combina los datos existentes con los nuevos datos
#combined_data = pd.concat([existing_data, new_data], ignore_index=True)

# Carga el DataFrame combinado en la hoja de cálculo
#gc.set_with_dataframe(worksheet, combined_data)

# Limpia la hoja de cálculo antes de cargar datos (opcional)
worksheet.clear()

# se suben los datos del DataFrame en la hoja de cálculo
set_with_dataframe(worksheet, df_sheets)  # Asegúrate de que gspread esté importado en tu código

print('Los datos se han cargado correctamente en Google Sheets.')

Los datos se han cargado correctamente en Google Sheets.